import org.cloudgarden.sotagparser.model.Question;
import org.cloudgarden.sotagparser.model.Wrapper;
import org.cloudgarden.sotagparser.service.StackoverflowService;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        final StackoverflowService stackoverflowService = new StackoverflowService();

        final Wrapper<Question> searchResult = stackoverflowService.search("activiti nullpointerexception", 1, 5);

        System.out.println("Search result: " + searchResult);
    }
}
