package org.cloudgarden.sotagparser;

import jodd.log.LoggerFactory;
import jodd.log.impl.Slf4jLoggerFactory;
import jodd.petite.PetiteContainer;
import jodd.petite.config.AutomagicPetiteConfigurator;
import jodd.props.Props;
import jodd.props.PropsUtil;
import org.cloudgarden.sotagparser.service.ParserService;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        final String query = getQueryOrDie(args);

        LoggerFactory.setLoggerFactory(new Slf4jLoggerFactory());

        final PetiteContainer petite = new PetiteContainer();
        new AutomagicPetiteConfigurator().configure(petite);

        final Props props = new Props();
        PropsUtil.loadFromClasspath(props, "/app*.props");
        petite.defineParameters(props);

        petite.getBean(ParserService.class).parseAndPrint(query);
    }

    private static String getQueryOrDie(String[] args) {
        if (args.length == 1) {
            return args[0];
        } else {
            System.out.println("ERROR: There should be only one argument - a query string");
            System.exit(255);
            return null; // to satisfy the compiler
        }
    }
}
