package org.cloudgarden.sotagparser;

import jodd.petite.PetiteContainer;
import jodd.petite.config.AutomagicPetiteConfigurator;
import jodd.props.Props;
import jodd.props.PropsUtil;
import org.cloudgarden.sotagparser.service.ParserService;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        final String query = "java generics";

        final PetiteContainer petite = new PetiteContainer();
        new AutomagicPetiteConfigurator().configure(petite);

        final Props props = new Props();
        PropsUtil.loadFromClasspath(props, "/app*.props");
        petite.defineParameters(props);

        petite.getBean(ParserService.class).parseAndPrint(query);
    }
}
